# Security and Performance Configuration for Production

# Security scanners and validators
security:
  # Container security scanning
  scan:
    - docker scout cves
    - trivy image football-simulation:prod
  
  # Network security
  network:
    - nmap localhost -p 80,443,3000
    - testssl.sh yourdomain.com
  
  # Application security
  application:
    - npm audit
    - pnpm audit
    - snyk test

# Performance monitoring
performance:
  # Load testing
  load_test:
    - apache_bench: ab -n 1000 -c 10 https://yourdomain.com/
    - wrk: wrk -t12 -c400 -d30s https://yourdomain.com/
  
  # Monitoring endpoints
  monitoring:
    - health: https://yourdomain.com/api/health
    - prometheus: http://yourdomain.com:9090/metrics
    - nginx_status: http://yourdomain.com/nginx_status

# Backup strategy
backup:
  # Application data
  app_backup:
    command: docker run --rm -v football_app_logs:/data -v $(pwd)/backups:/backup alpine tar czf /backup/app-backup-$(date +%Y%m%d).tar.gz /data
    schedule: "0 2 * * *"  # Daily at 2 AM
  
  # Database backup (if applicable)
  db_backup:
    command: docker exec postgres pg_dump -U user football_db > backups/db-backup-$(date +%Y%m%d).sql
    schedule: "0 1 * * *"  # Daily at 1 AM
  
  # SSL certificates backup
  ssl_backup:
    command: tar czf backups/ssl-backup-$(date +%Y%m%d).tar.gz ssl/
    schedule: "0 3 1 * *"  # Monthly

# Environment configurations
environments:
  development:
    domain: localhost
    ssl: self-signed
    monitoring: disabled
    caching: disabled
  
  staging:
    domain: staging.yourdomain.com
    ssl: letsencrypt
    monitoring: enabled
    caching: enabled
  
  production:
    domain: yourdomain.com
    ssl: letsencrypt
    monitoring: enabled
    caching: enabled
    redis: enabled
    backup: enabled

# Deployment checklist
deployment_checklist:
  pre_deployment:
    - [ ] Environment variables configured
    - [ ] SSL certificates obtained
    - [ ] Domain DNS configured
    - [ ] Firewall rules set
    - [ ] Backup strategy planned
  
  deployment:
    - [ ] Build production image
    - [ ] Start production services
    - [ ] Verify health checks
    - [ ] Test HTTPS
    - [ ] Verify SSL grade (A+)
  
  post_deployment:
    - [ ] Monitor application logs
    - [ ] Set up monitoring alerts
    - [ ] Configure log rotation
    - [ ] Test backup/restore
    - [ ] Document deployment process
